name: tempora
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.2.0+15

environment:
  sdk: '>=3.0.1 <4.0.0'
  flutter: '3.10.1'

dependencies:
  audioplayers: ^5.1.0
  auto_route: ^7.2.0
  collection: ^1.17.1
  dartz: ^0.10.1
  equatable: ^2.0.5
  firebase_analytics: ^10.4.4
  firebase_core: ^2.13.0
  firebase_crashlytics: ^3.3.1
  flutter:
    sdk: flutter
  flutter_background: ^1.2.0
  flutter_bloc: ^8.1.3
  flutter_local_notifications: ^14.1.0
  flutter_localizations:
        sdk: flutter
  flutter_slidable: ^3.0.0
  freezed_annotation: ^2.2.0
  get_it: ^7.6.0
  google_mobile_ads: ^3.0.0
  in_app_review: ^2.0.6
  intl: ^0.18.0
  json_annotation: ^4.8.1
  move_to_background: ^1.0.2
  package_info_plus: ^4.0.1
  path: ^1.8.3
  screen_state: ^3.0.1
  sqflite: ^2.2.8+4
  url_launcher: ^6.1.11
  uuid: ^3.0.7
  volume_controller: ^2.0.7

dev_dependencies:
  auto_route_generator: ^7.1.1
  build_runner: ^2.4.4
  faker: ^2.1.0
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0
  flutter_native_splash: ^2.3.1
  flutter_test:
    sdk: flutter
  freezed: ^2.3.4
  intl_utils: ^2.8.2
  json_serializable: ^6.7.0
  logger: ^1.3.0

flutter:

  uses-material-design: true
  assets:
    - assets/
    - assets/sounds/

flutter_icons:
  android: true
  image_path_android: "assets/launcher_icon/icon.png"
  adaptive_icon_background: "assets/launcher_icon/background.png"
  adaptive_icon_foreground: "assets/launcher_icon/foreground.png"
# Run this for icon generation:
# flutter pub run flutter_launcher_icons:main
  
flutter_intl:
  enabled: true
  main_locale: en
  class_name: S

# flutter pub run flutter_native_splash:create
# To restore Flutter's default white splash screen, run the following command in the terminal:
# flutter pub run flutter_native_splash:remove
flutter_native_splash:
  color: "#000000" 
  image: assets/launcher_icon/foreground.png

  branding: "assets/launcher_icon/branding_dark.png"

  android_12:
    color: "#000000" 
    image: assets/launcher_icon/foreground.png

  # The android, ios and web parameters can be used to disable generating a splash screen on a given
  # platform.
  android: true
  ios: false
  web: false
